Escape from SearchComposer with inputModeSearchKey
gureum/gureum pull request #762
Opened 2021-03-06 13:54 UTC by yous

Fix #761.

한자 단축키의 기본 값이 <kbd>option</kbd> + <kbd>return</kbd>이다보니 `IMKCandidates`에 먼저 들어가게 되어, 빠져나가려고 눌렀을 때 후보 선택이 됩니다. 그래서 이번에 `IMKCandidates`에 전달하는 input은 modifier가 없는 경우로 제한합니다. 화살표 키의 경우에는 modifier 값에 10485760이 추가되어 미리 제외합니다.

잠시 테스트해본 바로는 다음과 같이 동작합니다.

- <kbd>option</kbd> + <kbd>return</kbd>으로 연속 입력 모드 켬, 한글 입력 후 <kbd>return</kbd>으로 한자 변환, <kbd>option</kbd> + <kbd>return</kbd> 누르면 연속 입력 모드 꺼짐
- <kbd>option</kbd> + <kbd>return</kbd>으로 연속 입력 모드 켬, 한글 입력 도중 <kbd>option</kbd> + <kbd>return</kbd> 누르면 입력하던 한글 그대로 남은 채 연속 입력 모드 꺼짐
- 한글 입력 후 일부 선택 또는 한 글자 입력, <kbd>option</kbd> + <kbd>return</kbd> 눌러 한자 변환, 후보 창 닫힘. <kbd>option</kbd> + <kbd>return</kbd> 누르면 연속 입력 모드 켜짐
- 한글 입력 후 일부 선택 또는 한 글자 입력, <kbd>option</kbd> + <kbd>return</kbd> 누르면 후보 창 켜짐, <kbd>option</kbd> + <kbd>return</kbd> 누르면 입력하던 한글 그대로 남은 채 후보 창 닫힘

2021-03-06 16:12 UTC, youknowone requested changes
엄청나게 빠른 수정이네요 👍👍👍

2021-03-06 16:12 UTC, youknowone commented on OSXCore/InputController.swift
> +                let arrowModifier = NSEvent.ModifierFlags(rawValue: 10_485_760)
modifier는 bitmask라 리터럴로 쓰려면 `0xa00000`가 좋겠고, 아마 상수가 정의되어 있을거 같습니다. 다른 modifierflag 상수 타고 가보면 나올거 같아요.

2021-03-06 16:14 UTC, youknowone commented
유닛테스트 코드에서 OS 거치는 부분은 테스트가 어려운데, 이건 입력기 안쪽만이라 원하시면 동작 테스트도 추가할수 있을거 같아요

2021-03-06 17:04 UTC, yous commented on OSXCore/InputController.swift
> +                let arrowModifier = NSEvent.ModifierFlags(rawValue: 10_485_760)
네, 이건 한번 찾아보겠습니다.

2021-03-07 11:08 UTC, yous commented on OSXCore/InputController.swift
> +                let arrowModifier = NSEvent.ModifierFlags(rawValue: 10_485_760)
`.numericPad`와 `.function`의 조합이었네요. 0d069f7 커밋에서 고쳤습니다. [diff](https://github.com/gureum/gureum/compare/4aff4af3bfa5011e9ad2264834c65feb91518187..65bfa18abbf55130c1f9604fc0214e9f96314277)

2021-03-07 11:12 UTC, yous commented
지금 다시 빌드해보니 세 번째 항목이 재현되지 않네요.

예상 동작:
- 한글 입력 후 일부 선택 또는 한 글자 입력, <kbd>option</kbd> + <kbd>return</kbd> 눌러 한자 변환, 후보 창 닫힘. <kbd>option</kbd> + <kbd>return</kbd> 누르면 연속 입력 모드 켜짐

현재 동작:
- 한글 입력 후 일부 선택 또는 한 글자 입력, <kbd>option</kbd> + <kbd>return</kbd> 눌러 한자 변환, 후보 창 닫힘. <kbd>option</kbd> + <kbd>return</kbd> 눌러도 연속 입력 모드 켜지지 않음. 별도의 입력(화살표 등) 후 <kbd>option</kbd> + <kbd>return</kbd>을 눌러야 연속 입력 모드 켜짐.

2021-03-07 13:39 UTC, yous commented
기본적인 테스트는 4695681 커밋에서 추가했습니다.

2021-03-08 18:40 UTC, youknowone approved these changes

2021-03-08 18:41 UTC, merged